In [130]:
import numpy as np

# Numpy Array

In [131]:
myList = [10, 20, 30]

In [132]:
type(myList)

list

In [133]:
np.array(myList)

array([10, 20, 30])

In [134]:
type(np.array(myList))

numpy.ndarray

In [135]:
myMatrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [136]:
type(myMatrix)

list

In [137]:
np.array(myMatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## arange(start_index, finish_index, step)

In [138]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [139]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

## zeros(variable) or zeros((variable, variable))

In [141]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [142]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## ones(variable) or ones((variable, variable))

In [143]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [144]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## linspace(start_index, finish_index, piece)

In [145]:
np.linspace(0, 10, 6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

## eye(variable)  
identity matrix

In [146]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## random


<b>randn(x) :</b> Return a random array of x values

In [147]:
np.random.randn(3)

array([ 0.40037516,  0.94323272, -1.00102978])

In [148]:
np.random.randn(3, 3)

array([[-0.33482062, -0.27706829,  0.09847262],
       [ 0.45825282,  1.59625922, -0.6874653 ],
       [ 0.73926305, -0.77154524, -1.11534691]])

<b>randint(start_index, finish_index, piece):</b> Return a random integer variable from the defined range

In [149]:
np.random.randint(5, 12)

7

In [150]:
np.random.randint(1, 12, 3)

array([10,  5,  6])

# Numpy Array Methods

In [151]:
myArray = np.random.randint(1, 100, 30)

In [152]:
myArray

array([69, 39, 75, 27,  7,  7, 38, 52, 41, 22, 81, 71, 37, 80, 57, 75, 59,
       51, 18, 87, 72,  5, 60, 74, 12, 75, 95, 57, 67, 62])

## reshape(row, column)

In [153]:
myArray.reshape(6, 5)

array([[69, 39, 75, 27,  7],
       [ 7, 38, 52, 41, 22],
       [81, 71, 37, 80, 57],
       [75, 59, 51, 18, 87],
       [72,  5, 60, 74, 12],
       [75, 95, 57, 67, 62]])

## max() & min()

In [154]:
myArray.max()

95

In [155]:
myArray.min()

5

## argmax() & argmin()  
Return the index of the max or min value

In [156]:
myArray.argmax()

26

In [157]:
myArray.argmin()

21

# Numpy Array Attributes

## shape

In [158]:
myArray.shape

(30,)

In [159]:
myNewArray = myArray.reshape(5, 6)

In [160]:
myNewArray.shape

(5, 6)

# Numpy Indexes

In [161]:
arr = np.arange(0, 10)

In [162]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
arr[4]

4

In [164]:
arr[3:8]

array([3, 4, 5, 6, 7])

In [165]:
arr[3:8] = -5

In [166]:
arr

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9])

In [167]:
newArr = np.arange(0, 24)

In [168]:
newArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [169]:
slicingArray = newArr[:10]

In [170]:
slicingArray[:] = 700

In [171]:
newArr

array([700, 700, 700, 700, 700, 700, 700, 700, 700, 700,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

------------

In [172]:
newArray = np.arange(0, 24)

In [173]:
newArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [174]:
copyNewArray = newArray.copy()

In [175]:
copyNewArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [176]:
slicingNewArray = copyNewArray[:10]

In [177]:
slicingNewArray[:] = 700

In [178]:
copyNewArray

array([700, 700, 700, 700, 700, 700, 700, 700, 700, 700,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [179]:
newArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## Matrix

In [180]:
myList = [[10,20,30],[40,60,70],[80,90,100]]

In [181]:
myList = np.array(myList)

In [182]:
myList

array([[ 10,  20,  30],
       [ 40,  60,  70],
       [ 80,  90, 100]])

In [183]:
myList[0]

array([10, 20, 30])

In [184]:
myList[0][2]
# myList[0,2]

30

In [185]:
myList[0:,0]

array([10, 40, 80])

In [186]:
myList[1:,0]

array([40, 80])

In [188]:
myList[1:,0:]

array([[ 40,  60,  70],
       [ 80,  90, 100]])

In [189]:
myList[1:,0:2]

array([[40, 60],
       [80, 90]])

In [191]:
newList = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]]

In [192]:
newMatrix = np.array(newList)

In [193]:
newMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [194]:
newMatrix[[2,0,1]]

array([[10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

# Numpy Operations

In [197]:
newArray = np.random.randint(1,100,20)

In [198]:
newArray

array([65, 28, 13, 46, 77,  8, 52, 14, 91, 96, 52, 24, 49, 28, 88, 57, 58,
       25, 32, 44])

In [200]:
result = newArray > 24

In [201]:
result

array([ True,  True, False,  True,  True, False,  True, False,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True])

In [202]:
newArray[result]

array([65, 28, 46, 77, 52, 91, 96, 52, 49, 28, 88, 57, 58, 25, 32, 44])

In [203]:
newArray[newArray > 24]

array([65, 28, 46, 77, 52, 91, 96, 52, 49, 28, 88, 57, 58, 25, 32, 44])

In [204]:
arr = np.arange(0,24)

In [206]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [207]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [208]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [209]:
np.max(arr)

23

In [210]:
np.min(arr)

0